INSERT FILE='companion/spss/syntax/open-b01.sps'
 ERROR=STOP.
GET FILE='companion/spss/sav/b01.sav'.
FILTER OFF.
WEIGHT OFF.
SPLIT FILE OFF.
EXAMINE VARIABLES=g3 absences
 /PLOT=BOXPLOT HISTOGRAM
 /STATISTICS=DESCRIPTIVES /CINTERVAL=95.
FREQUENCIES VARIABLES=g3 /STATISTICS=MEDIAN.
