INSERT FILE='companion/spss/syntax/open-b01.sps'
 ERROR=STOP.
GET FILE='companion/spss/sav/b01.sav'.
FILTER OFF.
WEIGHT OFF.
SPLIT FILE OFF.
DISPLAY DICTIONARY.
FREQUENCIES VARIABLES=school sex studytime.
DESCRIPTIVES VARIABLES=age g3
 /STATISTICS=MEAN STDDEV MIN MAX.
